#!/bin/bash
#
# Script to compile patwarp
#
# Check to make sure WARP3D_HOME is set
#
[ -z "$WARP3D_HOME" ] && echo "Need to set WARP3D_HOME before proceeding." && exit 1
#
cd $WARP3D_HOME/patwarp
#
# Compiler must be installed
#
hash ifort 2>&- || { echo >&2 "The Intel fortran compiler is required (ifort).  Aborting."; exit 1;}
#
# Now proceed.
#
echo "Compiling patwarp on macOS ..."
ifort -O2 -xAVX -static-intel -w -traceback -fixed -fpe0 patwarp.f \
      -o $WARP3D_HOME/run_macOS/patwarp.go
#
echo "Executable is in run_macOS ..."
/bin/rm patwarp_data.mod
exit
